(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Rud0={Rud00,Rud01,Rud02,Rud03};
Tud0={Tud00,Tud01,Tud02,Tud03};
ferr0=rhou[[1]]-rho0;
ferr1=Table[(Rud[[1,ii]]-Rud0[[ii]])+dt*Gd[[ii]],{ii,1,4}];
ferr2=Table[(Tud[[1,ii]]-Tud0[[ii]])-dt*Gd[[ii]],{ii,1,4}];







(*
D1=D[rhou[[1]],{{rho,u,uut1,uut2,uut3,Er,urut1,urut2,urut3}}];
D2=D[Rud[[1]],{{rho,u,uut1,uut2,uut3,Er,urut1,urut2,urut3}}];
D3=D[Tud[[1]],{{rho,u,uut1,uut2,uut3,Er,urut1,urut2,urut3}}];

D1f=D[ferr0,{{rho,u,uut1,uut2,uut3,Er,urut1,urut2,urut3}}];
D2f=D[ferr1,{{rho,u,uut1,uut2,uut3,Er,urut1,urut2,urut3}}];
D3f=D[ferr2,{{rho,u,uut1,uut2,uut3,Er,urut1,urut2,urut3}}];

Dmatrix=Join[{D1},D2,D3];
iDmatrix=Inverse[Dmatrix];
*)



